CREATE DATABASE FISIO DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE FISIO;

CREATE TABLE Usuario ( 
  ID INT(11) AUTO_INCREMENT PRIMARY KEY, 
  NOME VARCHAR(255) NOT NULL, 
  LOGIN VARCHAR(255) NOT NULL, 
  SENHA INT(11) NOT NULL,
  ESTADO VARCHAR(255) NOT NULL 
 )ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;